import { redirect } from "next/navigation";

import { auth } from "@/auth";
import { AiOpsLogo, PoweredBy } from "@/components/brand/aiops-logo";
import { safeCallback } from "@/lib/safe-callback";

import { LoginForm } from "./login-form";

export const metadata = { title: "Sign in · AiOps" };

// Auth.js error codes → what the user can do about them.
const ERRORS: Record<string, string> = {
  AccessDenied: "Your account isn't allowed to sign in. Ask an admin for access.",
  Configuration: "Sign-in is misconfigured. Check the Keycloak settings in .env.",
  OAuthCallbackError: "Sign-in was cancelled or didn't complete. Try again.",
};

export default async function LoginPage({
  searchParams,
}: {
  searchParams: Promise<{ callbackUrl?: string; error?: string }>;
}) {
  const { callbackUrl, error } = await searchParams;
  const destination = safeCallback(callbackUrl, process.env.WEB_BASE_URL);
  if ((await auth())?.user) redirect(destination);

  return (
    <div className="grid min-h-screen grid-cols-[1.1fr_1fr] max-[820px]:grid-cols-1">
      <div className="flex flex-col justify-between gap-8 bg-term p-12 text-term-ink max-[820px]:px-6 max-[820px]:py-8">
        <AiOpsLogo onDark height={96} />
        <div>
          <h1 className="max-w-[15ch] text-[34px] tracking-[-0.02em] text-white">
            Ship any repo to any cloud, and see exactly what happened.
          </h1>
          <p className="mt-3.5 max-w-[44ch] text-term-muted">
            Answer a few questions, review the plan, deploy in one click. When something breaks, the
            agent reads the logs and tells you why.
          </p>
        </div>
        <pre className="m-0 font-mono text-[13px] leading-[1.7] whitespace-pre-wrap text-term-ink max-[820px]:hidden">
          <span className="text-term-muted"># runway.yaml</span>
          {"\n"}
          <span className="text-[#8FA7FF]">cloud:</span> aws{"  "}
          <span className="text-term-muted"># ap-south-1</span>
          {"\n"}
          <span className="text-[#8FA7FF]">source:</span> github.com/acme/payments-api@main
          {"\n"}
          <span className="text-[#8FA7FF]">target:</span> ecs-fargate
          {"\n"}
          <span className="text-[#8FA7FF]">build:</span> docker{" "}
          <span className="text-term-muted"># generated by agent</span>
          {"\n"}
          <span className="text-[#8FA7FF]">iac:</span> terraform
          {"\n"}
          <span className="text-[#8FA7FF]">pipeline:</span> github-actions, tests, approval
        </pre>
      </div>
      <div className="flex flex-col items-center justify-center gap-10 px-6 py-10">
        <LoginForm
          callbackUrl={destination}
          initialError={error ? (ERRORS[error] ?? "Sign-in didn't complete. Try again.") : ""}
        />
        <PoweredBy />
      </div>
    </div>
  );
}
